### ISSUE TITLE
If in the same match for more than 15 minutes, restart the service (e.g., restart the game)

### ISSUE THREAD

**Issue by RozyDagger** [ddm999/ClubmanSharp#65] opened 2023-11-11 04:18 UTC
Feature requested: As titled.

Bug description: With (maybe low but) non-zero probability, the vehicle gets stuck in the middle of the road while cannot resume the match normally for more than 60 minutes. Please add a listener thread to restart the game in this case.

**Comment by ddm999** [comment] 2023-11-12 15:04
duplicate of #11 , closing
This is something that's definitely on my todo list, but it might get delayed until after a rework for the new custom race grind

**Closed by ddm999** 2023-11-12 15:04 UTC
